### ISSUE TITLE
go get  error

### ISSUE THREAD

**Issue by sundy-li** [araddon/hive#2]
➜  ~  go get github.com/araddon/hive
# github.com/araddon/hive/thriftlib/hive_metastore
gopath/src/github.com/araddon/hive/thriftlib/hive_metastore/ThriftHiveMetastore.go:386: unknown ThriftHiveMetastoreClient field 'fb303.FacebookServiceClient' in struct literal
gopath/src/github.com/araddon/hive/thriftlib/hive_metastore/ThriftHiveMetastore.go:389: unknown ThriftHiveMetastoreClient field 'fb303.FacebookServiceClient' in struct literal

**Comment by plutov** [comment]
Can be closed now.

**Comment by araddon** [comment]
ty
